<?php

namespace MainBundle\Repository;

/**
 * AkciiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AkciiRepository extends \Doctrine\ORM\EntityRepository
{
}
