<?php

namespace MainBundle\Repository;

/**
 * BouquetSubscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BouquetSubscribeRepository extends \Doctrine\ORM\EntityRepository
{
}
