<?php

namespace MainBundle\Repository;

/**
 * CallRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CallRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
