<?php

namespace MainBundle\Repository;

/**
 * CatalogPaymentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogPaymentRepository extends \Doctrine\ORM\EntityRepository
{
}
