<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogSectionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogSectionRepository extends EntityRepository
{
}
