<?php

namespace MainBundle\Repository;

/**
 * IndividualBouquetRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IndividualBouquetRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
