<?php

namespace MainBundle\Repository;

/**
 * MailingSubscribeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingSubscribeRepository extends \Doctrine\ORM\EntityRepository
{
}
