<?php

namespace MainBundle\Repository;

/**
 * MailingTemplateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MailingTemplateRepository extends \Doctrine\ORM\EntityRepository
{
}
