<?php

namespace MainBundle\Repository;

/**
 * DeliveryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MainPageFigureRepository extends \Doctrine\ORM\EntityRepository
{
}
