<?php

namespace MainBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PriceRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRangeRepository extends EntityRepository
{
}
