<?php

namespace MainBundle\Repository;

/**
 * ServiceRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
